#!/usr/bin/env python3
"""Validate implementation plans generated by the writing-plans skill."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?", re.DOTALL)
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
TOPIC_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
TITLE_RE = re.compile(r"^# .+ Implementation Plan\s*$", re.MULTILINE)
TASK_HEADER_RE = re.compile(r"^### Task \d+: .+\S", re.MULTILINE)
TASK_SPLIT_RE = re.compile(r"(?=^### Task \d+: )", re.MULTILINE)
TABLE_HEADER_RE = re.compile(
    r"^\|\s*Requirement\s*\|\s*Proof command\s*\|\s*Expected signal\s*\|",
    re.IGNORECASE | re.MULTILINE,
)
HANDOFF_OPTION_RE = re.compile(r"^1\. .+", re.MULTILINE)

REQUIRED_HEADINGS = [
    "## Goal",
    "## Scope",
    "## Assumptions And Constraints",
    "## Task Breakdown",
    "## Risks And Mitigations",
    "## Verification Matrix",
    "## Handoff",
]

TASK_MARKERS = [
    "**Objective**",
    "**Files**",
    "**Dependencies**",
    "**Implementation Steps**",
    "**Verification**",
    "**Done When**",
]


def parse_frontmatter(text: str) -> tuple[dict[str, str], str, list[str]]:
    errors: list[str] = []
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text, ["Missing YAML frontmatter block at top of file"]

    raw = match.group(1)
    body = text[match.end() :]
    parsed: dict[str, str] = {}

    for line in raw.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if ":" not in stripped:
            errors.append(f"Invalid frontmatter line (expected key:value): {line}")
            continue
        key, value = stripped.split(":", 1)
        parsed[key.strip()] = value.strip().strip('"').strip("'")

    return parsed, body, errors


def validate_frontmatter(
    frontmatter: dict[str, str], expected_stage: str, strict_filename: bool, path: Path
) -> list[str]:
    errors: list[str] = []

    required = ["date", "topic", "stage", "status", "source"]
    for key in required:
        if key not in frontmatter or not frontmatter[key]:
            errors.append(f"Missing required frontmatter key: {key}")

    date_value = frontmatter.get("date", "")
    if date_value and not DATE_RE.match(date_value):
        errors.append("Frontmatter 'date' must match YYYY-MM-DD")

    topic_value = frontmatter.get("topic", "")
    if topic_value and not TOPIC_RE.match(topic_value):
        errors.append("Frontmatter 'topic' must be kebab-case")

    stage_value = frontmatter.get("stage", "")
    if stage_value and stage_value != expected_stage:
        errors.append(
            f"Frontmatter 'stage' must be '{expected_stage}', found '{stage_value}'"
        )

    if strict_filename and not path.name.endswith("-implementation.md"):
        errors.append("Filename must end with '-implementation.md' in strict mode")

    return errors


def validate_body(body: str) -> list[str]:
    errors: list[str] = []

    if not TITLE_RE.search(body):
        errors.append("Missing title '# ... Implementation Plan'")

    for heading in REQUIRED_HEADINGS:
        pattern = re.compile(rf"^{re.escape(heading)}\s*$", re.MULTILINE)
        if not pattern.search(body):
            errors.append(f"Missing required heading: {heading}")

    task_matches = list(TASK_HEADER_RE.finditer(body))
    if not task_matches:
        errors.append("Missing task blocks (expected '### Task N: ...')")
    else:
        task_blocks = [
            block for block in TASK_SPLIT_RE.split(body) if block.startswith("### Task ")
        ]
        for block in task_blocks:
            first_line = block.splitlines()[0].strip()
            for marker in TASK_MARKERS:
                if marker not in block:
                    errors.append(f"{first_line}: missing required marker {marker}")

    if not TABLE_HEADER_RE.search(body):
        errors.append(
            "Missing verification matrix table header '| Requirement | Proof command | Expected signal |'"
        )

    if not HANDOFF_OPTION_RE.search(body):
        errors.append("Handoff section must include numbered options starting at '1.'")

    return errors


def validate_file(path: Path, expected_stage: str, strict_filename: bool) -> list[str]:
    errors: list[str] = []
    if not path.exists():
        return [f"File not found: {path}"]
    if path.suffix.lower() != ".md":
        return [f"Not a markdown file: {path}"]

    text = path.read_text(encoding="utf-8")
    frontmatter, body, fm_errors = parse_frontmatter(text)
    errors.extend(fm_errors)

    if not fm_errors:
        errors.extend(
            validate_frontmatter(frontmatter, expected_stage, strict_filename, path)
        )

    errors.extend(validate_body(body))
    return errors


def iter_markdown_files(paths: list[Path]) -> list[Path]:
    files: list[Path] = []
    for path in paths:
        if path.is_dir():
            files.extend(sorted(path.rglob("*.md")))
        else:
            files.append(path)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate writing-plans implementation plan markdown files."
    )
    parser.add_argument("paths", nargs="+", help="Markdown files or directories to scan")
    parser.add_argument(
        "--expected-stage",
        default="implementation-plan",
        help="Required frontmatter stage value (default: implementation-plan)",
    )
    parser.add_argument(
        "--strict-filename",
        action="store_true",
        help="Require filenames to end with '-implementation.md'",
    )
    args = parser.parse_args()

    targets = iter_markdown_files([Path(p) for p in args.paths])
    if not targets:
        print("No markdown files found.")
        return 1

    has_errors = False
    for target in targets:
        errors = validate_file(target, args.expected_stage, args.strict_filename)
        if errors:
            has_errors = True
            print(f"FAIL: {target}")
            for error in errors:
                print(f"  - {error}")
        else:
            print(f"PASS: {target}")

    return 1 if has_errors else 0


if __name__ == "__main__":
    sys.exit(main())
