#!/usr/bin/env python3
"""Validate plans generated by the write-plan skill.

A plan is the execution artifact: task breakdown, files, ordered steps, and
verification commands that realize a write-spec contract. This validator
enforces the plan schema (the original write-spec plan schema, moved here when
write-spec became the contract skill).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?", re.DOTALL)
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
TOPIC_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
TITLE_RE = re.compile(r"^# .+ Plan\s*$", re.MULTILINE)
TASK_HEADER_RE = re.compile(r"^### Task \d+: .+\S", re.MULTILINE)
TASK_SPLIT_RE = re.compile(r"(?=^### Task \d+: )", re.MULTILINE)
TABLE_HEADER_RE = re.compile(
    r"^\|\s*Requirement\s*\|\s*Proof command\s*\|\s*Expected signal\s*\|",
    re.IGNORECASE | re.MULTILINE,
)
HANDOFF_OPTION_RE = re.compile(r"^1\. .+", re.MULTILINE)
FILES_SECTION_RE = re.compile(
    r"^\*\*Files\*\*:?[ \t]*(.*?)(?=^\*\*[^*]+?\*\*|\Z)",
    re.MULTILINE | re.DOTALL,
)
MODIFY_FILE_RE = re.compile(
    r"^\s*[-*]\s*Modify(?:\s*\([^)]*\))?:", re.IGNORECASE | re.MULTILINE
)
TEST_FILE_LABEL_RE = re.compile(
    r"^\s*[-*]\s*Test(?:\s*\([^)]*\))?:", re.IGNORECASE | re.MULTILINE
)
INLINE_CODE_RE = re.compile(r"`([^`]+)`")

REQUIRED_HEADINGS = [
    "## Goal",
    "## Scope",
    "## Assumptions And Constraints",
    "## Task Breakdown",
    "## Risks And Mitigations",
    "## Verification Matrix",
    "## Handoff",
]

TASK_MARKERS = [
    "**Objective**",
    "**Files**",
    "**Dependencies**",
    "**Implementation Steps**",
    "**Verification**",
    "**Done When**",
]


def iter_task_blocks(body: str) -> list[str]:
    """Return task blocks without trying to interpret their free prose."""
    return [
        block for block in TASK_SPLIT_RE.split(body) if block.startswith("### Task ")
    ]


def task_files_block(task: str) -> str:
    """Return a task's bounded Files content, or an empty string when absent."""
    match = FILES_SECTION_RE.search(task)
    return match.group(1) if match else ""


def is_test_path(path: str) -> bool:
    """Recognize common test-file locations without treating prose as a path."""
    normalized = path.strip().replace("\\", "/")
    filename = normalized.rsplit("/", 1)[-1].lower()
    return (
        "/tests/" in f"/{normalized.lower()}"
        or filename.startswith("test_")
        or filename.startswith("test-")
        or ".test." in filename
        or ".spec." in filename
        or filename.endswith("_test.py")
    )


def task_changes_tests(files: str) -> bool:
    """Detect explicit test-file entries in a Files block."""
    if TEST_FILE_LABEL_RE.search(files):
        return True
    return any(is_test_path(path) for path in INLINE_CODE_RE.findall(files))


def collect_advisories(body: str) -> list[str]:
    """Return non-blocking grounding nudges for task metadata.

    The signals are deliberately narrow: only explicit entries in a task's
    ``Files`` block participate. They cannot determine whether a citation or
    test command is truthful, so callers must never convert these messages into
    schema failures.
    """
    advisories: list[str] = []

    for task in iter_task_blocks(body):
        first_line = task.splitlines()[0].strip()
        files = task_files_block(task)
        if not files:
            continue

        if MODIFY_FILE_RE.search(files) and "**Assumptions Verified**" not in task:
            advisories.append(
                f"{first_line[4:]}: modifies existing code but has no "
                "**Assumptions Verified** marker"
            )

        if task_changes_tests(files) and "**Test Discovery Verified**" not in task:
            advisories.append(
                f"{first_line[4:]}: changes tests but has no "
                "**Test Discovery Verified** marker"
            )

    return advisories


def parse_frontmatter(text: str) -> tuple[dict[str, str], str, list[str]]:
    errors: list[str] = []
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text, ["Missing YAML frontmatter block at top of file"]

    raw = match.group(1)
    body = text[match.end() :]
    parsed: dict[str, str] = {}

    for line in raw.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if ":" not in stripped:
            errors.append(f"Invalid frontmatter line (expected key:value): {line}")
            continue
        key, value = stripped.split(":", 1)
        parsed[key.strip()] = value.strip().strip('"').strip("'")

    return parsed, body, errors


def validate_frontmatter(
    frontmatter: dict[str, str], expected_stage: str, strict_filename: bool, path: Path
) -> list[str]:
    errors: list[str] = []

    required = ["date", "topic", "stage", "status", "source"]
    for key in required:
        if key not in frontmatter or not frontmatter[key]:
            errors.append(f"Missing required frontmatter key: {key}")

    date_value = frontmatter.get("date", "")
    if date_value and date_value != "YYYY-MM-DD" and not DATE_RE.match(date_value):
        errors.append("Frontmatter 'date' must match YYYY-MM-DD")

    topic_value = frontmatter.get("topic", "")
    if topic_value and not TOPIC_RE.match(topic_value):
        errors.append("Frontmatter 'topic' must be kebab-case")

    stage_value = frontmatter.get("stage", "")
    if stage_value and stage_value != expected_stage:
        errors.append(
            f"Frontmatter 'stage' must be '{expected_stage}', found '{stage_value}'"
        )

    if strict_filename and not path.name.endswith("-plan.md"):
        errors.append("Filename must end with '-plan.md' in strict mode")

    return errors


def validate_body(body: str) -> list[str]:
    errors: list[str] = []

    if not TITLE_RE.search(body):
        errors.append("Missing title '# ... Plan'")

    for heading in REQUIRED_HEADINGS:
        pattern = re.compile(rf"^{re.escape(heading)}\s*$", re.MULTILINE)
        if not pattern.search(body):
            errors.append(f"Missing required heading: {heading}")

    task_matches = list(TASK_HEADER_RE.finditer(body))
    if not task_matches:
        errors.append("Missing task blocks (expected '### Task N: ...')")
    else:
        for block in iter_task_blocks(body):
            first_line = block.splitlines()[0].strip()
            for marker in TASK_MARKERS:
                if marker not in block:
                    errors.append(f"{first_line}: missing required marker {marker}")

    if not TABLE_HEADER_RE.search(body):
        errors.append(
            "Missing verification matrix table header '| Requirement | Proof command | Expected signal |'"
        )

    if not HANDOFF_OPTION_RE.search(body):
        errors.append("Handoff section must include numbered options starting at '1.'")

    return errors


def validate_file(path: Path, expected_stage: str, strict_filename: bool) -> list[str]:
    errors: list[str] = []
    if not path.exists():
        return [f"File not found: {path}"]
    if path.suffix.lower() != ".md":
        return [f"Not a markdown file: {path}"]

    text = path.read_text(encoding="utf-8")
    frontmatter, body, fm_errors = parse_frontmatter(text)
    errors.extend(fm_errors)

    if not fm_errors:
        errors.extend(
            validate_frontmatter(frontmatter, expected_stage, strict_filename, path)
        )

    errors.extend(validate_body(body))
    return errors


def iter_markdown_files(paths: list[Path]) -> list[Path]:
    files: list[Path] = []
    for path in paths:
        if path.is_dir():
            files.extend(sorted(path.rglob("*.md")))
        else:
            files.append(path)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate write-plan plan markdown files."
    )
    parser.add_argument("paths", nargs="+", help="Markdown files or directories to scan")
    parser.add_argument(
        "--expected-stage",
        default="plan",
        help="Required frontmatter stage value (default: plan)",
    )
    parser.add_argument(
        "--strict-filename",
        action="store_true",
        help="Require filenames to end with '-plan.md'",
    )
    args = parser.parse_args()

    targets = iter_markdown_files([Path(p) for p in args.paths])
    if not targets:
        print("No markdown files found.")
        return 1

    has_errors = False
    for target in targets:
        errors = validate_file(target, args.expected_stage, args.strict_filename)
        if errors:
            has_errors = True
            print(f"FAIL: {target}")
            for error in errors:
                print(f"  - {error}")
        else:
            print(f"PASS: {target}")

        if not target.is_file():
            continue

        text = target.read_text(encoding="utf-8")
        _, body, frontmatter_errors = parse_frontmatter(text)
        if not frontmatter_errors:
            for advisory in collect_advisories(body):
                print(f"ADVISORY: {target}")
                print(f"  - {advisory}")

    return 1 if has_errors else 0


if __name__ == "__main__":
    sys.exit(main())
