#!/usr/bin/env python3
"""Validate plans generated by the write-plan skill.

A plan is the execution artifact: task breakdown, files, ordered steps, and
verification commands that realize a write-spec contract. This validator
enforces the plan schema (the original write-spec plan schema, moved here when
write-spec became the contract skill).
"""

from __future__ import annotations

import argparse
from collections import Counter
import re
import subprocess
import sys
from pathlib import Path


FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?", re.DOTALL)
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
TOPIC_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
TITLE_RE = re.compile(r"^# .+ Plan\s*$", re.MULTILINE)
TASK_HEADER_RE = re.compile(r"^### Task \d+: .+\S", re.MULTILINE)
TASK_SPLIT_RE = re.compile(r"(?=^### Task \d+: )", re.MULTILINE)
TABLE_HEADER_RE = re.compile(
    r"^\|\s*Requirement\s*\|\s*Proof command\s*\|\s*Expected signal\s*\|",
    re.IGNORECASE | re.MULTILINE,
)
HANDOFF_OPTION_RE = re.compile(r"^1\. .+", re.MULTILINE)
FILES_SECTION_RE = re.compile(
    r"^\*\*Files\*\*:?[ \t]*(.*?)(?=^\*\*[^*]+?\*\*|\Z)",
    re.MULTILINE | re.DOTALL,
)
MODIFY_FILE_RE = re.compile(
    r"^\s*[-*]\s*Modify(?:\s*\([^)]*\))?:", re.IGNORECASE | re.MULTILINE
)
TEST_FILE_LABEL_RE = re.compile(
    r"^\s*[-*]\s*Test(?:\s*\([^)]*\))?:", re.IGNORECASE | re.MULTILINE
)
INLINE_CODE_RE = re.compile(r"`([^`]+)`")
ASSUMPTIONS_VERIFIED_SECTION_RE = re.compile(
    r"^\*\*Assumptions Verified\*\*(?::[ \t]*.*)?[ \t]*$", re.MULTILINE
)
TEST_DISCOVERY_VERIFIED_SECTION_RE = re.compile(
    r"^\*\*Test Discovery Verified\*\*(?::[ \t]*.*)?[ \t]*$", re.MULTILINE
)
DEPENDENCIES_SECTION_RE = re.compile(
    r"^\*\*Dependencies\*\*:?[ \t]*(.*?)(?=^\*\*[^*]+?\*\*|\Z)",
    re.MULTILINE | re.DOTALL,
)
DONE_WHEN_SECTION_RE = re.compile(
    r"^\*\*Done When\*\*:?[ \t]*(.*?)(?=^\*\*[^*]+?\*\*|\Z)",
    re.MULTILINE | re.DOTALL,
)
TASK_NUMBER_RE = re.compile(r"^### Task (\d+): ", re.MULTILINE)
CONTRACT_ID_RE = re.compile(r"\b(?:SC-\d{2}|EV-(?:NEG|REC|CON|LEG)-\d{2})\b")
WEAK_ACCEPTANCE_PATTERNS = (
    ("bare > 0", re.compile(r">\s*0(?![\d.])")),
    ("not empty", re.compile(r"\bnot\s+empty\b", re.IGNORECASE)),
    (
        "completion-only wording",
        re.compile(r"\b(?:completes?|prints?)\b", re.IGNORECASE),
    ),
)
HIGH_RISK_SUBHEADINGS = [
    "### Traceability",
    "### Capability And Authority Map",
    "### Side Effects And Failure Windows",
    "### Evidence Lifecycle",
    "### Consumer Closure",
    "### Lifecycle And Compatibility",
    "### Execution Hooks",
    "### Capability Stop Gates",
    "### Readiness Review",
]
HIGH_RISK_TABLE_HEADERS = {
    "Traceability": "| Contract ID | Task | Proof |",
    "Capability And Authority Map": (
        "| Actor | Allowed | Forbidden | Effective-runtime proof |"
    ),
    "Side Effects And Failure Windows": "| Effect | Before | After | Recovery |",
    "Evidence Lifecycle": (
        "| Evidence | Trusted producer | Created | Claim | Consumers | Freshness |"
    ),
}

REQUIRED_HEADINGS = [
    "## Goal",
    "## Scope",
    "## Assumptions And Constraints",
    "## Task Breakdown",
    "## Risks And Mitigations",
    "## Verification Matrix",
    "## Handoff",
]

TASK_MARKERS = [
    "**Objective**",
    "**Files**",
    "**Dependencies**",
    "**Implementation Steps**",
    "**Verification**",
    "**Done When**",
]


def iter_task_blocks(body: str) -> list[str]:
    """Return task blocks without trying to interpret their free prose."""
    return [
        block for block in TASK_SPLIT_RE.split(body) if block.startswith("### Task ")
    ]


def task_files_block(task: str) -> str:
    """Return a task's bounded Files content, or an empty string when absent."""
    match = FILES_SECTION_RE.search(task)
    return match.group(1) if match else ""


def is_test_path(path: str) -> bool:
    """Recognize common test-file locations without treating prose as a path."""
    normalized = path.strip().replace("\\", "/")
    filename = normalized.rsplit("/", 1)[-1].lower()
    return (
        "/tests/" in f"/{normalized.lower()}"
        or filename.startswith("test_")
        or filename.startswith("test-")
        or ".test." in filename
        or ".spec." in filename
        or filename.endswith("_test.py")
    )


def task_changes_tests(files: str) -> bool:
    """Detect explicit test-file entries in a Files block."""
    if TEST_FILE_LABEL_RE.search(files):
        return True
    return any(is_test_path(path) for path in INLINE_CODE_RE.findall(files))


def has_marker_section(task: str, marker_section_re: re.Pattern[str]) -> bool:
    """Return whether a task defines a marker field, not merely mentions it."""
    return marker_section_re.search(task) is not None


def collect_advisories(body: str) -> list[str]:
    """Return non-blocking grounding nudges for task metadata.

    The signals are deliberately narrow: only explicit entries in a task's
    ``Files`` block participate. They cannot determine whether a citation or
    test command is truthful, so callers must never convert these messages into
    schema failures.
    """
    advisories: list[str] = []

    for task in iter_task_blocks(body):
        first_line = task.splitlines()[0].strip()
        files = task_files_block(task)
        if not files:
            continue

        if MODIFY_FILE_RE.search(files) and not has_marker_section(
            task, ASSUMPTIONS_VERIFIED_SECTION_RE
        ):
            advisories.append(
                f"{first_line[4:]}: modifies existing code but has no "
                "**Assumptions Verified** marker"
            )

        if task_changes_tests(files) and not has_marker_section(
            task, TEST_DISCOVERY_VERIFIED_SECTION_RE
        ):
            advisories.append(
                f"{first_line[4:]}: changes tests but has no "
                "**Test Discovery Verified** marker"
            )

    done_when_text = "\n".join(
        match.group(1) for match in DONE_WHEN_SECTION_RE.finditer(body)
    )
    weak_signals = [
        label
        for label, pattern in WEAK_ACCEPTANCE_PATTERNS
        if pattern.search(done_when_text)
    ]
    if weak_signals:
        advisories.append(
            "Plan acceptance uses weak signals "
            f"({', '.join(weak_signals)}); require a pinned magnitude, floor, "
            "rate, or non-degeneracy bound"
        )

    return advisories


def parse_frontmatter(text: str) -> tuple[dict[str, str], str, list[str]]:
    errors: list[str] = []
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text, ["Missing YAML frontmatter block at top of file"]

    raw = match.group(1)
    body = text[match.end() :]
    parsed: dict[str, str] = {}

    for line in raw.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if ":" not in stripped:
            errors.append(f"Invalid frontmatter line (expected key:value): {line}")
            continue
        key, value = stripped.split(":", 1)
        parsed[key.strip()] = value.strip().strip('"').strip("'")

    return parsed, body, errors


def validate_frontmatter(
    frontmatter: dict[str, str], expected_stage: str, strict_filename: bool, path: Path
) -> list[str]:
    errors: list[str] = []

    required = ["date", "topic", "stage", "status", "source"]
    if "risk_profile" in frontmatter or "readiness" in frontmatter:
        required.append("author")
    for key in required:
        if key not in frontmatter or not frontmatter[key]:
            errors.append(f"Missing required frontmatter key: {key}")

    if frontmatter.get("author") == "<agent>":
        errors.append("Frontmatter 'author' must name the producing agent")

    date_value = frontmatter.get("date", "")
    if date_value and date_value != "YYYY-MM-DD" and not DATE_RE.match(date_value):
        errors.append("Frontmatter 'date' must match YYYY-MM-DD")

    topic_value = frontmatter.get("topic", "")
    if topic_value and not TOPIC_RE.match(topic_value):
        errors.append("Frontmatter 'topic' must be kebab-case")

    stage_value = frontmatter.get("stage", "")
    if stage_value and stage_value != expected_stage:
        errors.append(
            f"Frontmatter 'stage' must be '{expected_stage}', found '{stage_value}'"
        )

    if strict_filename and not path.name.endswith("-plan.md"):
        errors.append("Filename must end with '-plan.md' in strict mode")

    return errors


def validate_body(body: str) -> list[str]:
    errors: list[str] = []

    if not TITLE_RE.search(body):
        errors.append("Missing title '# ... Plan'")

    for heading in REQUIRED_HEADINGS:
        pattern = re.compile(rf"^{re.escape(heading)}\s*$", re.MULTILINE)
        if not pattern.search(body):
            errors.append(f"Missing required heading: {heading}")

    task_matches = list(TASK_HEADER_RE.finditer(body))
    if not task_matches:
        errors.append("Missing task blocks (expected '### Task N: ...')")
    else:
        for block in iter_task_blocks(body):
            first_line = block.splitlines()[0].strip()
            for marker in TASK_MARKERS:
                if marker not in block:
                    errors.append(f"{first_line}: missing required marker {marker}")

    if not TABLE_HEADER_RE.search(body):
        errors.append(
            "Missing verification matrix table header '| Requirement | Proof command | Expected signal |'"
        )

    if not HANDOFF_OPTION_RE.search(body):
        errors.append("Handoff section must include numbered options starting at '1.'")

    return errors


def section_body(body: str, heading: str) -> str | None:
    """Return text beneath a level-two or level-three heading."""
    level = heading.split(" ", 1)[0]
    pattern = re.compile(
        rf"^{re.escape(heading)}\s*$(.*?)(?=^{re.escape(level)} |\Z)",
        re.MULTILINE | re.DOTALL,
    )
    match = pattern.search(body)
    return match.group(1) if match else None


def discover_repo_root(path: Path) -> Path:
    """Find the target artifact's Git root, falling back to the caller's cwd."""
    start = path if path.is_dir() else path.parent
    try:
        proc = subprocess.run(
            ["git", "-C", str(start), "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:
        proc = None
    if proc is not None and proc.returncode == 0 and proc.stdout.strip():
        return Path(proc.stdout.strip()).resolve()
    return Path.cwd().resolve()


def resolve_repo_path(raw: str, repo_root: Path) -> Path | None:
    """Resolve a repository-relative path without allowing an escape."""
    candidate = Path(raw)
    if candidate.is_absolute() or ".." in candidate.parts:
        return None
    root = repo_root.resolve()
    resolved = (root / candidate).resolve()
    try:
        resolved.relative_to(root)
    except ValueError:
        return None
    return resolved


def task_dependency_errors(body: str) -> list[str]:
    errors: list[str] = []
    blocks = iter_task_blocks(body)
    task_numbers = [int(number) for number in TASK_NUMBER_RE.findall(body)]
    for number, count in Counter(task_numbers).items():
        if count > 1:
            errors.append(f"High-risk plan has duplicate task number Task {number}")

    known = set(task_numbers)
    for block in blocks:
        first_line = block.splitlines()[0].strip()
        match = DEPENDENCIES_SECTION_RE.search(block)
        if not match:
            continue
        for dependency in re.findall(r"\bTask (\d+)\b", match.group(1)):
            if int(dependency) not in known:
                errors.append(f"{first_line[4:]}: unknown dependency Task {dependency}")
    return errors


def traceability_task_errors(body: str, high_risk_section: str) -> list[str]:
    errors: list[str] = []
    known = {int(number) for number in TASK_NUMBER_RE.findall(body)}
    traceability = section_body(high_risk_section, "### Traceability") or ""
    for task_number in re.findall(r"\bTask (\d+)\b", traceability):
        if int(task_number) not in known:
            errors.append(
                f"High-risk plan traceability references unknown Task {task_number}"
            )
    return errors


def modified_file_errors(body: str, repo_root: Path) -> list[str]:
    errors: list[str] = []
    for task in iter_task_blocks(body):
        files = task_files_block(task)
        for line in files.splitlines():
            if not re.match(r"^\s*[-*]\s*Modify(?:\s*\([^)]*\))?:", line, re.IGNORECASE):
                continue
            for raw in INLINE_CODE_RE.findall(line):
                target = resolve_repo_path(raw, repo_root)
                if target is None:
                    errors.append(f"High-risk plan has invalid repository path: {raw}")
                elif not target.exists():
                    errors.append(f"High-risk plan cites missing modified file: {raw}")
    return errors


def validate_high_risk(
    frontmatter: dict[str, str],
    body: str,
    path: Path,
    repo_root: Path | None = None,
) -> list[str]:
    """Validate the conditional high-risk planning extension."""
    errors: list[str] = []
    risk_profile = frontmatter.get("risk_profile", "routine")
    readiness = frontmatter.get("readiness", "draft")

    if risk_profile not in {"routine", "high"}:
        errors.append("Frontmatter 'risk_profile' must be 'routine' or 'high'")
    if readiness not in {"draft", "ready"}:
        errors.append("Frontmatter 'readiness' must be 'draft' or 'ready'")
    if risk_profile != "high":
        return errors
    resolved_repo_root = (
        repo_root.resolve() if repo_root is not None else discover_repo_root(path)
    )

    if "readiness" not in frontmatter:
        errors.append("High-risk plans must declare frontmatter 'readiness'")

    high_risk_section = section_body(body, "## High-Risk Readiness")
    if high_risk_section is None:
        errors.append("High-risk plan missing required heading: ## High-Risk Readiness")
    else:
        for heading in HIGH_RISK_SUBHEADINGS:
            if section_body(high_risk_section, heading) is None:
                errors.append(f"High-risk plan missing required heading: {heading}")
        for label, header in HIGH_RISK_TABLE_HEADERS.items():
            if header not in high_risk_section:
                errors.append(f"High-risk plan missing required {label} table header")

    spec_value = frontmatter.get("spec", "")
    if not spec_value:
        errors.append("High-risk plans must link a repository-relative spec in frontmatter 'spec'")
    else:
        spec_path = resolve_repo_path(spec_value, resolved_repo_root)
        if spec_path is None:
            errors.append("High-risk plan frontmatter 'spec' must be repository-relative")
        elif not spec_path.exists():
            errors.append(f"High-risk plan linked spec does not exist: {spec_value}")
        else:
            spec_text = spec_path.read_text(encoding="utf-8")
            spec_frontmatter, _, spec_parse_errors = parse_frontmatter(spec_text)
            if spec_parse_errors:
                errors.append(f"High-risk plan linked spec has invalid frontmatter: {spec_value}")
            elif spec_frontmatter.get("risk_profile") != "high":
                errors.append("High-risk plan must link a spec with risk_profile: high")
            elif spec_frontmatter.get("readiness") != "ready":
                errors.append("High-risk plan requires linked spec with readiness: ready")

            spec_ids = set(CONTRACT_ID_RE.findall(spec_text))
            plan_ids = set(CONTRACT_ID_RE.findall(body))
            if not spec_ids:
                errors.append("High-risk linked spec must define SC-NN and EV-*-NN IDs")
            for identifier in sorted(spec_ids - plan_ids):
                errors.append(f"High-risk plan does not cover linked spec ID {identifier}")
            for identifier in sorted(plan_ids - spec_ids):
                errors.append(f"High-risk plan references unknown linked spec ID {identifier}")

    errors.extend(task_dependency_errors(body))
    errors.extend(traceability_task_errors(body, high_risk_section or ""))
    errors.extend(modified_file_errors(body, resolved_repo_root))

    if readiness == "ready":
        review = section_body(high_risk_section or "", "### Readiness Review") or ""
        critique_markers = [
            r"^- Deterministic validation:\s*passed\s*$",
            r"^- Adversarial critique:\s*complete\s*$",
            r"^- Closure critique:\s*complete\s*$",
        ]
        if not all(
            re.search(marker, review, re.IGNORECASE | re.MULTILINE)
            for marker in critique_markers
        ):
            errors.append(
                "High-risk plan readiness requires deterministic validation, "
                "adversarial critique, and closure critique"
            )
        if not re.search(
            r"^- Blocking findings:\s*none\s*$",
            review,
            re.IGNORECASE | re.MULTILINE,
        ):
            errors.append("High-risk plan cannot be ready while blocking findings remain")

    return errors


def validate_file(
    path: Path,
    expected_stage: str,
    strict_filename: bool,
    repo_root: Path | None = None,
) -> list[str]:
    errors: list[str] = []
    if not path.exists():
        return [f"File not found: {path}"]
    if path.suffix.lower() != ".md":
        return [f"Not a markdown file: {path}"]

    text = path.read_text(encoding="utf-8")
    frontmatter, body, fm_errors = parse_frontmatter(text)
    errors.extend(fm_errors)

    if not fm_errors:
        errors.extend(
            validate_frontmatter(frontmatter, expected_stage, strict_filename, path)
        )

    errors.extend(validate_body(body))
    errors.extend(validate_high_risk(frontmatter, body, path, repo_root))
    return errors


def iter_markdown_files(paths: list[Path]) -> list[Path]:
    files: list[Path] = []
    for path in paths:
        if path.is_dir():
            files.extend(sorted(path.rglob("*.md")))
        else:
            files.append(path)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate write-plan plan markdown files."
    )
    parser.add_argument("paths", nargs="+", help="Markdown files or directories to scan")
    parser.add_argument(
        "--expected-stage",
        default="plan",
        help="Required frontmatter stage value (default: plan)",
    )
    parser.add_argument(
        "--strict-filename",
        action="store_true",
        help="Require filenames to end with '-plan.md'",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        help=(
            "Repository root for spec and modified-file paths. Defaults to each "
            "plan's Git root; outside Git, defaults to the current directory."
        ),
    )
    args = parser.parse_args()

    targets = iter_markdown_files([Path(p) for p in args.paths])
    if not targets:
        print("No markdown files found.")
        return 1

    repo_root = args.repo_root.resolve() if args.repo_root else None
    if repo_root is not None and not repo_root.is_dir():
        print(f"Repository root is not a directory: {repo_root}")
        return 1

    has_errors = False
    for target in targets:
        errors = validate_file(
            target,
            args.expected_stage,
            args.strict_filename,
            repo_root,
        )
        if errors:
            has_errors = True
            print(f"FAIL: {target}")
            for error in errors:
                print(f"  - {error}")
        else:
            print(f"PASS: {target}")

        if errors or not target.is_file():
            continue

        text = target.read_text(encoding="utf-8")
        _, body, frontmatter_errors = parse_frontmatter(text)
        if not frontmatter_errors:
            for advisory in collect_advisories(body):
                print(f"ADVISORY: {target}")
                print(f"  - {advisory}")

    return 1 if has_errors else 0


if __name__ == "__main__":
    sys.exit(main())
