#!/usr/bin/env python3
"""Validate contracts generated by the write-spec skill.

A spec is a *contract*: a mechanism-free statement of the target (problem,
falsifiable end-state, success criteria, evaluation). It must NOT carry plan
content (task breakdowns, file lists, ordered implementation steps) -- those
belong to the write-plan skill. This validator enforces both: the contract
schema is present, and plan-shaped sections are absent.
"""

from __future__ import annotations

import argparse
from collections import Counter
import re
import sys
from pathlib import Path

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?", re.DOTALL)
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
TOPIC_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
TITLE_RE = re.compile(r"^# .+ Spec\s*$", re.MULTILINE)
HANDOFF_OPTION_RE = re.compile(r"^1\. .+", re.MULTILINE)
INLINE_CODE_RE = re.compile(r"`[^`]+`")

REQUIRED_HEADINGS = [
    "## Problem",
    "## Contract",
    "## Success Criteria",
    "## Evaluation",
    "## Scope",
    "## Assumptions And Constraints",
    "## Open Questions",
    "## Handoff",
]

# Plan-shaped content that must NOT appear in a contract -- it belongs in the
# write-plan artifact. Keeps spec-ness structural rather than advisory.
FORBIDDEN_HEADINGS = [
    "## Task Breakdown",
    "## Verification Matrix",
]
FORBIDDEN_MARKERS = [
    "**Implementation Steps**",
    "**Files**",
]
FORBIDDEN_TASK_HEADER_RE = re.compile(r"^### Task \d+: ", re.MULTILINE)
SUCCESS_CRITERION_ID_RE = re.compile(r"\bSC-\d{2}\b")
SCENARIO_ID_RE = re.compile(r"\bEV-(?:NEG|REC|CON|LEG)-\d{2}\b")
HIGH_RISK_HEADINGS = [
    "## Authority And Safety",
    "## Evaluation Scenarios",
    "## Readiness Review",
]
SCENARIO_CLASSES = {
    "negative": "EV-NEG-",
    "recovery": "EV-REC-",
    "concurrency": "EV-CON-",
    "legacy": "EV-LEG-",
}


def parse_frontmatter(text: str) -> tuple[dict[str, str], str, list[str]]:
    errors: list[str] = []
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text, ["Missing YAML frontmatter block at top of file"]

    raw = match.group(1)
    body = text[match.end() :]
    parsed: dict[str, str] = {}

    for line in raw.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if ":" not in stripped:
            errors.append(f"Invalid frontmatter line (expected key:value): {line}")
            continue
        key, value = stripped.split(":", 1)
        parsed[key.strip()] = value.strip().strip('"').strip("'")

    return parsed, body, errors


def validate_frontmatter(
    frontmatter: dict[str, str], expected_stage: str, strict_filename: bool, path: Path
) -> list[str]:
    errors: list[str] = []

    required = ["date", "topic", "stage", "status", "source"]
    if "risk_profile" in frontmatter or "readiness" in frontmatter:
        required.append("author")
    for key in required:
        if key not in frontmatter or not frontmatter[key]:
            errors.append(f"Missing required frontmatter key: {key}")

    if frontmatter.get("author") == "<agent>":
        errors.append("Frontmatter 'author' must name the producing agent")

    date_value = frontmatter.get("date", "")
    if date_value and date_value != "YYYY-MM-DD" and not DATE_RE.match(date_value):
        errors.append("Frontmatter 'date' must match YYYY-MM-DD")

    topic_value = frontmatter.get("topic", "")
    if topic_value and not TOPIC_RE.match(topic_value):
        errors.append("Frontmatter 'topic' must be kebab-case")

    stage_value = frontmatter.get("stage", "")
    if stage_value and stage_value != expected_stage:
        errors.append(
            f"Frontmatter 'stage' must be '{expected_stage}', found '{stage_value}'"
        )

    if strict_filename and not path.name.endswith("-spec.md"):
        errors.append("Filename must end with '-spec.md' in strict mode")

    return errors


def section_body(body: str, heading: str) -> str | None:
    """Return the text from `heading` up to the next `## ` heading, or None."""
    pattern = re.compile(
        rf"^{re.escape(heading)}\s*$(.*?)(?=^## |\Z)", re.MULTILINE | re.DOTALL
    )
    match = pattern.search(body)
    return match.group(1) if match else None


def validate_body(body: str) -> list[str]:
    errors: list[str] = []

    if not TITLE_RE.search(body):
        errors.append("Missing title '# ... Spec'")

    for heading in REQUIRED_HEADINGS:
        pattern = re.compile(rf"^{re.escape(heading)}\s*$", re.MULTILINE)
        if not pattern.search(body):
            errors.append(f"Missing required heading: {heading}")

    # The Contract must be falsifiable: at least one verification command
    # (inline code span) stating how the end-state is checked.
    contract = section_body(body, "## Contract")
    if contract is not None and not INLINE_CODE_RE.search(contract):
        errors.append(
            "Contract section must name at least one verification command "
            "(an inline `code` span) that makes the end-state falsifiable"
        )

    # Plan-shaped content is forbidden -- it belongs in write-plan.
    for heading in FORBIDDEN_HEADINGS:
        pattern = re.compile(rf"^{re.escape(heading)}\s*$", re.MULTILINE)
        if pattern.search(body):
            errors.append(
                f"Forbidden plan-shaped heading in a contract: {heading} "
                "(move to a write-plan plan)"
            )
    for marker in FORBIDDEN_MARKERS:
        if marker in body:
            errors.append(
                f"Forbidden plan-shaped marker in a contract: {marker} "
                "(move to a write-plan plan)"
            )
    if FORBIDDEN_TASK_HEADER_RE.search(body):
        errors.append(
            "Forbidden plan-shaped '### Task N:' block in a contract "
            "(move to a write-plan plan)"
        )

    if not HANDOFF_OPTION_RE.search(body):
        errors.append("Handoff section must include numbered options starting at '1.'")

    return errors


def validate_high_risk(frontmatter: dict[str, str], body: str) -> list[str]:
    """Validate the conditional high-risk contract extension."""
    errors: list[str] = []
    risk_profile = frontmatter.get("risk_profile", "routine")
    readiness = frontmatter.get("readiness", "draft")

    if risk_profile not in {"routine", "high"}:
        errors.append("Frontmatter 'risk_profile' must be 'routine' or 'high'")
    if readiness not in {"draft", "ready"}:
        errors.append("Frontmatter 'readiness' must be 'draft' or 'ready'")
    if risk_profile != "high":
        return errors

    if "readiness" not in frontmatter:
        errors.append("High-risk contracts must declare frontmatter 'readiness'")

    for heading in HIGH_RISK_HEADINGS:
        if section_body(body, heading) is None:
            errors.append(f"High-risk contract missing required heading: {heading}")

    criteria = section_body(body, "## Success Criteria") or ""
    criterion_ids = SUCCESS_CRITERION_ID_RE.findall(criteria)
    if not criterion_ids:
        errors.append("High-risk contract must give success criteria stable SC-NN IDs")
    for identifier, count in Counter(criterion_ids).items():
        if count > 1:
            errors.append(f"High-risk contract has duplicate success criterion ID {identifier}")

    scenarios = section_body(body, "## Evaluation Scenarios") or ""
    scenario_ids = SCENARIO_ID_RE.findall(scenarios)
    for identifier, count in Counter(scenario_ids).items():
        if count > 1:
            errors.append(f"High-risk contract has duplicate evaluation scenario ID {identifier}")
    for label, prefix in SCENARIO_CLASSES.items():
        if not any(identifier.startswith(prefix) for identifier in scenario_ids):
            errors.append(
                f"High-risk contract must include a {label} evaluation scenario "
                f"with an {prefix}NN ID"
            )

    if readiness == "ready":
        review = section_body(body, "## Readiness Review") or ""
        critique_markers = [
            r"^- Deterministic validation:\s*passed\s*$",
            r"^- Adversarial critique:\s*complete\s*$",
            r"^- Closure critique:\s*complete\s*$",
        ]
        if not all(
            re.search(marker, review, re.IGNORECASE | re.MULTILINE)
            for marker in critique_markers
        ):
            errors.append(
                "High-risk contract readiness requires deterministic validation, "
                "adversarial critique, and closure critique"
            )
        if not re.search(
            r"^- Blocking findings:\s*none\s*$",
            review,
            re.IGNORECASE | re.MULTILINE,
        ):
            errors.append(
                "High-risk contract cannot be ready while blocking findings remain"
            )

    return errors


def validate_file(path: Path, expected_stage: str, strict_filename: bool) -> list[str]:
    errors: list[str] = []
    if not path.exists():
        return [f"File not found: {path}"]
    if path.suffix.lower() != ".md":
        return [f"Not a markdown file: {path}"]

    text = path.read_text(encoding="utf-8")
    frontmatter, body, fm_errors = parse_frontmatter(text)
    errors.extend(fm_errors)

    if not fm_errors:
        errors.extend(
            validate_frontmatter(frontmatter, expected_stage, strict_filename, path)
        )

    errors.extend(validate_body(body))
    errors.extend(validate_high_risk(frontmatter, body))
    return errors


def iter_markdown_files(paths: list[Path]) -> list[Path]:
    files: list[Path] = []
    for path in paths:
        if path.is_dir():
            files.extend(sorted(path.rglob("*.md")))
        else:
            files.append(path)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate write-spec contract markdown files."
    )
    parser.add_argument("paths", nargs="+", help="Markdown files or directories to scan")
    parser.add_argument(
        "--expected-stage",
        default="spec",
        help="Required frontmatter stage value (default: spec)",
    )
    parser.add_argument(
        "--strict-filename",
        action="store_true",
        help="Require filenames to end with '-spec.md'",
    )
    args = parser.parse_args()

    targets = iter_markdown_files([Path(p) for p in args.paths])
    if not targets:
        print("No markdown files found.")
        return 1

    has_errors = False
    for target in targets:
        errors = validate_file(target, args.expected_stage, args.strict_filename)
        if errors:
            has_errors = True
            print(f"FAIL: {target}")
            for error in errors:
                print(f"  - {error}")
        else:
            print(f"PASS: {target}")

    return 1 if has_errors else 0


if __name__ == "__main__":
    sys.exit(main())
